language: python
python:
  - "2.7"
install:
  - pip -V # Get info on pip to debug install problems.
  - pip install --upgrade pip
  - pip -V
  - "pip install -r requirements.txt"
script:
  - python cluster_app_test.py
  # And as a sanity check, make sure the server actually runs:
  - export FLASK_APP=cluster_app.py
  - flask run
  - URL='http://localhost:5000/cluster?matrix=[[0],[100],[101],[1]]'
  - "[[ `curl -g $URL` == '[0, 3, 1, 2]' ]] && echo 'PASS!'"
